# For more see https://gohugo.io/content-management/menus/

main:                # sections in the website sidebar
  - identifier: home # section id
    name: Home       # section display title
    url: /           # path to the section
    weight: 1        # order of sections

  - identifier: about
    name: About
    url: /about/
    weight: 2

  - identifier: posts
    name: Posts
    url: /posts/
    weight: 5

  - identifier: search
    name: Search
    url: /search/
    weight: 5

  - identifier: contact
    name: Contact
    url: /contact/
    weight: 6
